
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace fir {

class block_node;
class bracket_node;
class declaration_variable_node;
class evaluation_node;
class function_call_node;
class function_declaration_node;
class function_definition_node;
class identify_node;
class if_else_node;
class if_node;
class leave_node;
class left_value_node;
class null_pointer_node;
class pointer_node;
class print_node;
class program_node;
class read_node;
class restart_node;
class return_node;
class size_of_node;
class while_finally_node;
class while_node;
class write_node;


} // namespace fir

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_fir_NODE_ALLNODES_H__
#define __AUTOMATIC_fir_NODE_ALLNODES_H__

#include "ast/block_node.h"
#include "ast/bracket_node.h"
#include "ast/declaration_variable_node.h"
#include "ast/evaluation_node.h"
#include "ast/function_call_node.h"
#include "ast/function_declaration_node.h"
#include "ast/function_definition_node.h"
#include "ast/identify_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/leave_node.h"
#include "ast/left_value_node.h"
#include "ast/null_pointer_node.h"
#include "ast/pointer_node.h"
#include "ast/print_node.h"
#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/restart_node.h"
#include "ast/return_node.h"
#include "ast/size_of_node.h"
#include "ast/while_finally_node.h"
#include "ast/while_node.h"
#include "ast/write_node.h"


#endif /* !defined(__AUTOMATIC_fir_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

